
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
export function OpenMotorPopUp(tagPrefix, posX, posY) {
  OpenScreenHMIRuntime.UI.SysFct.OpenScreenInPopup("tagPrefix", "LBC_MotorStarterExtended", false, "", posX, posY, false, undefined);
}
