
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
/**
This function checks if the specified hmiNo is the same as the enabledHmiControlNo and if the ipAdress is the same as the ipControl, if not returns false value 
as a button in a LBC faceplate that access this script should not be able to be pressed in that HMI.

Change log: 
    1. 20-04-2026: Modified by - Siemens Digital Industries, Reason - First implementation.  



*/
export function Function(hmiNo, hmiNoControl, pressed, enableManualCmds, ipAddress, ipAddressControl) {

      if(enableManualCmds) {
         //Check if the specified HMI is the same as the enabled control one
         if ((hmiNo == hmiNoControl) && (ipAddress == ipAddressControl)){   
         return true;
         } 
         else{
           //Check if the button was already pressed and mantain action if it was due to safety reasons
           if (!pressed){
           return false;
           }
         } 
      }
      else{
         if (!pressed){
         return false;
         }

      }

}
