
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
/**
This function opens a prepared LBC popup screen dynamically by giving the HMI tag, graphic list and text list to the popup name. 
With this method, only 1 popup screen is needed without using multiplexing.

Inputs:
moduleInterface : String - HMI Tag for faceplate
graphicListName : String - Graphic list with the symbols for the faceplate
buttonsTextListName : String - Text list with buttons texts
screenToOpen : String - screen name to be open as a popup with the LBC faceplates
*/
export function Open_LBCPopup(moduleInterface, screenToOpen, graphicListName, buttonsTextList) {
let popupWindowName;

// Check if a module interface was give, else don't try to open popup
if (moduleInterface == undefined || moduleInterface == '') {
  HMIRuntime.Trace("No moduleInterface was given for the Popup script");
  return;
}

try {
// Prepare popup screen name with correct format
popupWindowName = `${moduleInterface}&&${graphicListName}&&${buttonsTextList}`;
} catch (err){
HMIRuntime.Trace("Error while parsing screen name for the Popup name")
HMIRuntime.Trace(err.message)
} 


//Open screen in popup with configuration
HMIRuntime.UI.SysFct.OpenScreenInPopup(popupWindowName, screenToOpen, true, "", 100, 100, true, undefined);
}
/**
This function returns the tag name for the module interface, the graphic list and the buttons text list for loading dynamically a screen on the loaded event.

Outputs:
moduleInterface : String - HMI Tag for faceplate
graphicListName : String - Graphic list with the symbols for the faceplate
buttonsTextListName : String - Text list with buttons texts
*/
export function Load_LBCPopup() {
  const scrnName = Screen.CurrentWindow.Name;
  const nameArray = scrnName.split("&&");
  const moduleInterface = nameArray[0];
  const graphicListName  = "GraphicListCollection."+ nameArray[1];
  const buttonsTextListName  = "@Default."+nameArray[2];

return [moduleInterface, graphicListName, buttonsTextListName ];
}
